### ISSUE TITLE
Eccezioni file

### ISSUE THREAD

**Issue by danielemontesi** [dataslang/dataslang-xml-tools#3]
Ho provato il comando 'validate' passando prima l'xml con il percorso sbagliato e viene lanciata l'eccezione 'Impossibile trovare il file specificato'. Ho fatto la stessa cosa per l'xsd e l'eccezione è diversa. Dovrebbe essere uguale alla prima?

**Comment by Tbaile** [comment]
Ho trovato la causa, una volta tira l'eccezione FileNotFound, l'altra una SAXException, commit in arrivo
