### ISSUE TITLE
Esito validazione

### ISSUE THREAD

**Issue by danielemontesi** [dataslang/dataslang-xml-tools#4]
Il comando per la validazione dovrebbe mostrare un messaggio se l'xml è valido

**Comment by danielemontesi** [comment]
La stessa cosa per la transformazione se non metto l'opzione output

**Comment by Tbaile** [comment]
Vuoi qualcosa di specifico o un banale "true" o " false"? Se non erro il software ritorna il codice chiusura 0 se corretto o altro se non lo è

**Comment by danielemontesi** [comment]
Per la validazione andrebbe bene semplicemente 'File valido' e per la trasformazione 'Trasformazione riuscita'
